apiVersion: v1
kind: Pod
metadata:
  name: pod-micro-1
  labels:
    app: app-micro-1
spec:
  containers:
    - name: nodejs
      image: tsubaki0x01/payment:1.0.0
      ports:
        - containerPort: 6800
    - name: redisdb
      image: tsubaki0x01/redis_sevice:1.0.0
      ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: service-pod
spec:
  selector: 
    app: app-micro-1
  ports:
    - protocol: TCP
      port: 6800
      targetPort: 6800
      nodePort: 30001
  type: NodePort
